language: python
python:
  - "2.7"
services:
  - neo4j
install:
  - pip install -r requirements-dev.txt --use-wheel
  - pip install -e . --use-wheel
  - pip install coveralls --use-wheel
script:
  - py.test goggles -v -s
after_success:
  - coveralls

