language: python
sudo: false
python:
  - "2.7"
cache:
  directories:
    - $HOME/.pip-cache/
    - /home/travis/virtualenv/python2.7
install:
  - pip install -e . --download-cache $HOME/.pip-cache --allow-external treq
  - pip install -r requirements-dev.txt --download-cache $HOME/.pip-cache
  - pip install coveralls --download-cache $HOME/.pip-cache
before_script:
  - psql -c "CREATE DATABASE goggles WITH ENCODING='UTF8' OWNER=DEFAULT TEMPLATE=template0;" -U postgres
script:
  - ./run_tests.sh
after_success:
  - coveralls
